# Generated by Django 4.2.21 on 2025-05-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_distancebaseprice_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='distanceadditionalprice',
            name='applies_after_km',
            field=models.FloatField(default=3.0),
        ),
    ]
