# Generated by Django 4.2.21 on 2025-05-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_distanceadditionalprice_applies_after_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingconfig',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
