# Generated by Django 4.2.21 on 2025-05-20 19:44

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_distancebaseprice_pricing_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distancebaseprice',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=30),
        ),
    ]
