# Generated by Django 4.2.21 on 2025-05-20 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_distancebaseprice_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distanceadditionalprice',
            name='pricing_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_prices', to='webapp.pricingconfig'),
        ),
        migrations.AlterField(
            model_name='timemultiplierfactor',
            name='pricing_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_multipliers', to='webapp.pricingconfig'),
        ),
        migrations.AlterField(
            model_name='waitingcharge',
            name='pricing_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_charges', to='webapp.pricingconfig'),
        ),
    ]
